
version: 1.2.0

cde-databases:
  - concentric

services:
  - php:
      version: 7.1

events:
  build:
    steps:
      # If you have build instructions, put them here. They are not required.
    - build_site:
        script:
            - composer update
            - git status


post-deploy:
  steps:
    - deploy:
            script:
            - pipelines-deploy
            - pipelines-sync-dbs concentric

# When a GitHub pull request is merged, this deletes the coresponding ODE.
pr-merged:
    steps:
    - deploy:
        script:
            - pipelines-deploy

# When a GitHub pull request is closed, this deletes the coresponding ODE.
pr-closed:
    steps:
    - deploy:
        script:
            - pipelines-deploy
